# Generated by Django 3.1.13 on 2021-08-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_personaldetail_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='how_good',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=13, null=True),
        ),
    ]
