# Generated by Django 3.1.13 on 2021-08-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210819_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='how_good',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('EXPERT', 'EXPERT')], max_length=13, null=True),
        ),
    ]
