# Generated by Django 3.1.13 on 2021-08-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20210819_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
