# Generated by Django 3.1.13 on 2021-08-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_education_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='course_name',
        ),
    ]
